routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function () {
    return view('auth_template');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('masterchecklists', 'MasterChecklistController')->except(['show']);
Route::resource('users', 'UserController')->except(['show']);
Route::resource('nearmisses', 'NearmissController');
Route::resource('locations', 'LocationController')->except(['show']);
Route::resource('departments', 'DepartmentController')->except(['show']);

Route::resource('checklists', 'ChecklistController');
Route::resource('checklistitems', 'ChecklistItemController')->only(['edit','update']);
Route::resource('temuans', 'TemuanController');
Route::resource('temuanitems', 'TemuanItemController');

Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin']], function() {

    Route::get('/users/{id}/change-roles', 'UserController@changeRole')->name('change-roles');
    Route::post('/users/{id}/save-roles', 'UserController@saveRole')->name('save-roles');
    Route::get('/users/{id}/loginbyid', 'UserController@loginById')->name('loginbyid');
    Route::get('/users/{id}/reset-password', 'UserController@resetPassword')->name('reset-password');

    Route::get('mastercheklists-by-category/{id}', 'MasterChecklistController@indexByCategory')->name('mastercheklists-by-category');
    Route::get('mastercheklists-create-by-category/{id}', 'MasterChecklistController@createByCategory')->name('mastercheklists-create-by-category');

    Route::put('/departments/{id}/sethead/{user_id}', 'DepartmentController@sethead')->name('sethead');
});

Route::group(['prefix' => '/', 'middleware' => ['auth']], function() {
    Route::get('/change-password/user', 'ChangePasswordController@create')->name('change-password.create');
    Route::post('/change-password/user', 'ChangePasswordController@store')->name('change-password.store');

    Route::get('/checklists/{id}/print', 'ChecklistController@print')->name('checklists.print');
    Route::get('/temuans/{id}/print', 'TemuanController@print')->name('temuans.print');
    Route::get('/nearmisses/{id}/print', 'NearmissController@print')->name('nearmisses.print');
    Route::get('/temuans/{id}/create-by-checklist', 'TemuanController@createByChecklist')->name('temuans.createbychecklist');
    Route::get('/temuanitems/{id}/create-by-temuan', 'TemuanItemController@createByTemuan')->name('temuanitems.createbytemuan');
});

Route::group(['prefix' => '/', 'middleware' => ['role:safety']], function (){
    Route::post('checklistitems/skip-action/{id}/{action}', 'ChecklistItemController@skip')->name('checklistitems.skip');
});
Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin|safety']], function() {
    Route::get('walkdowninspectors/walkdown/{id}/list', 'WalkdownInspectorController@list')->name('walkdowninspectors.list');
    Route::post('walkdowninspectors/walkdown/{id}/add', 'WalkdownInspectorController@add')->name('walkdowninspectors.add');
    Route::delete('walkdowninspectors/{id}/delete', 'WalkdownInspectorController@destroy')->name('walkdowninspectors.destroy');
});

resources/views/admin_template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ isset($page_title)  ? $page_title.' - ' : ''}} {{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ asset("/bower_components/bootstrap/dist/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{{ asset("/bower_components/font-awesome/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{{ asset("/bower_components/select2/dist/css/select2.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ asset("/bower_components/Ionicons/css/ionicons.min.css") }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/bower_components/jquery-ui/themes/base/jquery-ui.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Timepicker -->
    <link href="{{ asset("/plugins/timepicker/timepicker.css") }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/plugins/featherlight-1.7.13/src/featherlight.css") }}" rel="stylesheet" type="text/css" />
    <!-- datatables.net -->
    <link href="{{ asset("/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/dist/css/skins/_all-skins.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body class="{{ auth()->user()->getUserTheme() }}">
<div class="wrapper">

    <!-- Header -->
    @include('layouts.header')

    <!-- Sidebar -->
    @include('layouts.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <div style="padding: 10px 10px 0px 10px">
            @include('flash::message')
        </div>

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $page_title or "Page Title" }}
                <small>{{ $page_description or null }}</small>
            </h1>
            <!-- You can dynamically generate breadcrumbs here -->
            {{--<ol class="breadcrumb">--}}
                {{--<li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>--}}
                {{--<li class="active">Here</li>--}}
            {{--</ol>--}}
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('layouts.footer')

</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.1.3 -->
<script src="{{ asset ("/bower_components/jquery/dist/jquery.min.js") }}"></script>
<!-- datatable.net -->
<script src="{{ asset ("/bower_components/datatables.net/js/jquery.dataTables.min.js") }}"></script>
<script src="{{ asset ("/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js") }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset ("/bower_components/bootstrap/dist/js/bootstrap.min.js") }}" type="text/javascript"></script>
<!-- Select2 -->
<script src="{{ asset ("/bower_components/select2/dist/js/select2.min.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/bower_components/jquery-ui/jquery-ui.min.js")}}"></script>
<!-- timepicker -->
<script src="{{ asset ("/plugins/timepicker/timepicker.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/plugins/featherlight-1.7.13/src/featherlight.js") }}" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{{ asset ("/dist/js/adminlte.min.js") }}" type="text/javascript"></script>

<script>
    $( document ).ready(function () {
        $('#flash-overlay-modal').modal();
        $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
    });
</script>

@yield('inline-script')
</body>
</html>

resources/views/auth_template.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ isset($page_title)  ? $page_title.' - ' : ''}} {{ config('app.name') }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.2 -->
  <link href="{{ asset("/bower_components/bootstrap/dist/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{{ asset("/bower_components/font-awesome/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ asset("/bower_components/Ionicons/css/ionicons.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset("/bower_components/admin-lte/plugins/iCheck/square/blue.css")}}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
@yield('content')

<!-- /.login-box -->

<!-- jQuery 3 -->
<!-- jQuery 2.1.3 -->
<script src="{{ asset ("/bower_components/jquery/dist/jquery.min.js") }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset ("/bower_components/bootstrap/dist/js/bootstrap.min.js") }}" type="text/javascript"></script>
<!-- iCheck -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/iCheck/icheck.min.js") }}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

resources/views/home.blade.php
@extends('admin_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="card">
                <div class="card-header">
                    Selamat datang {{ auth()->user()->name }} !
                    <br/><br/>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3 col-sm-4 col-xs-12">
                            <div class="info-box">
                                <span class="info-box-icon bg-aqua">
                                    <i class="fa fa-ambulance"></i>
                                </span>
                                @php( $count_nearmiss = count(auth()->user()->nearmissCreated) )
                                @role(['admin', 'superadmin', 'safety'])
                                    @php( $count_nearmiss = $count_all_nearmiss )
                                @endrole

                                <div class="info-box-content">
                                    <span class="info-box-text">Nearmiss</span>
                                    <span class="info-box-number">
                                        @role(['admin', 'superadmin', 'safety'])
                                            {{ count(auth()->user()->nearmissCreated) }} /
                                        @endrole
                                        {{ $count_nearmiss }}
                                    </span>
                                    <div class="pull-right">
                                        <a href="{{ route('nearmisses.index') }}"
                                           class="btn btn-default btn-sm">
                                            <i class="fa fa-list"></i>
                                        </a>
                                        <a href="{{ route('nearmisses.create') }}" title="Buat Baru"
                                           class="btn btn-primary btn-sm">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                                <!-- /.info-box-content -->
                            </div>
                            <!-- /.info-box -->
                        </div>

                        @role(['admin', 'superadmin', 'safety'])
                        <div class="col-md-3 col-sm-4 col-xs-12">
                            <div class="info-box">
                                <span class="info-box-icon bg-olive">
                                    <i class="fa fa-check"></i>
                                </span>

                                <div class="info-box-content">
                                    <span class="info-box-text">Walkdown</span>
                                    <span class="info-box-number">{{ $count_all_walkdown }}</span>
                                    <div class="pull-right">
                                        <a href="{{ route('checklists.index') }}"
                                           class="btn btn-default btn-sm">
                                            <i class="fa fa-list"></i>
                                        </a>
                                        @role('safety')
                                        <a href="{{ route('checklists.create') }}" title="Buat Baru"
                                           class="btn btn-primary btn-sm">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                        @endrole
                                    </div>
                                </div>
                                <!-- /.info-box-content -->
                            </div>
                            <!-- /.info-box -->
                        </div>
                        @endrole
                    </div>
                </div>
            </div>
    </div>
</div>
@endsection

resources/views/print_template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "Cetak" }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ asset("/bower_components/bootstrap/dist/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{{ asset("/bower_components/font-awesome/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <!-- Ionicons -->
    <link href="{{ asset("/bower_components/Ionicons/css/ionicons.min.css") }}" rel="stylesheet" type="text/css" />
    <link href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
        @media print {
            .menu-container {
                visibility: hidden;
            }
        }
        @media screen {
            .menu-container{
                margin: 10px 25px;
            }
        }
    </style>
</head>
<body>
<div class="wrapper" style="overflow: visible">

    <section class="menu-container">
        <button onclick="window.print();">Print</button>
        <button onclick="window.close();">Close</button>
    </section>

    <section class="invoice">
        
        <!-- header -->
        <div class="row">
            <div class="col-xs-12">
              <h2 class="page-header">
                <i class="fa fa-globe">Nama Perusahaan</i>
              </h2>
            </div>
        </div>
        
        <!-- info -->
        @yield('content')
    </section>

</div><!-- ./wrapper -->

<!-- AdminLTE App -->
<script src="{{ asset ("/dist/js/adminlte.min.js") }}" type="text/javascript"></script>

@yield('inline-script')
</body>
</html>