routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function () {
    return view('auth_template');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('masterchecklists', 'MasterChecklistController')->except(['show']);
Route::resource('users', 'UserController')->except(['show']);
Route::resource('nearmisses', 'NearmissController');
Route::resource('locations', 'LocationController')->except(['show']);
Route::resource('departments', 'DepartmentController')->except(['show']);

Route::resource('checklists', 'ChecklistController');
Route::resource('checklistitems', 'ChecklistItemController')->only(['edit','update']);
Route::resource('temuans', 'TemuanController');
Route::resource('temuanitems', 'TemuanItemController');

Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin']], function() {

    Route::get('/users/{id}/change-roles', 'UserController@changeRole')->name('change-roles');
    Route::post('/users/{id}/save-roles', 'UserController@saveRole')->name('save-roles');
    Route::get('/users/{id}/loginbyid', 'UserController@loginById')->name('loginbyid');
    Route::get('/users/{id}/reset-password', 'UserController@resetPassword')->name('reset-password');

    Route::get('mastercheklists-by-category/{id}', 'MasterChecklistController@indexByCategory')->name('mastercheklists-by-category');
    Route::get('mastercheklists-create-by-category/{id}', 'MasterChecklistController@createByCategory')->name('mastercheklists-create-by-category');

    Route::put('/departments/{id}/sethead/{user_id}', 'DepartmentController@sethead')->name('sethead');
});

Route::group(['prefix' => '/', 'middleware' => ['auth']], function() {
    Route::get('/change-password/user', 'ChangePasswordController@create')->name('change-password.create');
    Route::post('/change-password/user', 'ChangePasswordController@store')->name('change-password.store');

    Route::get('/checklists/{id}/print', 'ChecklistController@print')->name('checklists.print');
    Route::get('/temuans/{id}/print', 'TemuanController@print')->name('temuans.print');
    Route::get('/nearmisses/{id}/print', 'NearmissController@print')->name('nearmisses.print');
    Route::get('/temuans/{id}/create-by-checklist', 'TemuanController@createByChecklist')->name('temuans.createbychecklist');
    Route::get('/temuanitems/{id}/create-by-temuan', 'TemuanItemController@createByTemuan')->name('temuanitems.createbytemuan');
});

Route::group(['prefix' => '/', 'middleware' => ['role:safety']], function (){
    Route::post('checklistitems/skip-action/{id}/{action}', 'ChecklistItemController@skip')->name('checklistitems.skip');
});
Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin|safety']], function() {
    Route::get('walkdowninspectors/walkdown/{id}/list', 'WalkdownInspectorController@list')->name('walkdowninspectors.list');
    Route::post('walkdowninspectors/walkdown/{id}/add', 'WalkdownInspectorController@add')->name('walkdowninspectors.add');
    Route::delete('walkdowninspectors/{id}/delete', 'WalkdownInspectorController@destroy')->name('walkdowninspectors.destroy');
});

app/Models/Temuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Temuan extends Model
{
    public function creator()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function location()
    {
        return $this->belongsTo('App\Models\Location');
    }

    public function temuanItems()
    {
        return $this->hasMany('App\Models\TemuanItem', 'temuan_id', 'id');
    }

    public function checklist()
    {
        return $this->belongsTo('App\Models\Checklist');
    }
}

app/Http/Controllers/TemuanController.php
<?php

namespace App\Http\Controllers;

use App\Forms\TemuanForm;
use App\Models\Checklist;
use App\Models\Temuan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class TemuanController extends Controller
{
    use FormBuilderTrait;
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin|superadmin|safety');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'Daftar Temuan';
        $page_description = 'Temuan';

        if(Auth::user()->hasRole('admin')){
            $temuans = Temuan::all();
        }else{
            $temuans = Auth::user()->temuanCreated;
        }

        return view('temuans.index', compact('temuans', 'page_title', 'page_description'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createByChecklist($id)
    {
        $page_title = 'Buat temuan';
        $checklist = Checklist::find($id);
        $temuan = new Temuan;
        $temuan->checklist_id = $checklist->id;
        $temuan->location_id = $checklist->location_id;
        $temuan->inspection_date = $checklist->inspection_date;

        $form = $this->form(TemuanForm::class, [
            'method'    => 'POST',
            'url' => route('temuans.store'),
            'model' => $temuan
        ]);

        return view('temuans.create', compact('form', 'page_title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(TemuanForm::class);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->getFieldValues();
        $temuan = new Temuan;
        $temuan->user_id = Auth::user()->id;
        $temuan->checklist_id = $data['checklist_id'];
        $temuan->department_id = $data['department_id'];
        $temuan->location_id = $data['location_id'];
        $temuan->inspection_date = $data['inspection_date'];
        $temuan->save();

        flash('Data temuan berhasil disimpan.')->success();
        return redirect('/temuans');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $temuan = Temuan::find($id);
        $page_title = 'Daftar Item Temuan';

        return view('temuans.show', compact('temuan', 'page_title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function print($id)
    {
        $temuan = Temuan::find($id);
        $type = 'Temuan';

        return view('temuans.print', compact('temuan', 'type'));
    }
}

resources/views/temuans/create.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
          <h3 class="box-title">
              Form Temuan
          </h3>
        </div>
        <!-- /.box-header -->
            
        <div class="box-body">
            {!! form($form) !!}
        </div>
    </div>

@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            //Date picker
            $('.datepicker').datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
@endsection

resources/views/temuans/index.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Tabel Temuan
            </h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body" style="overflow-x: scroll">
            <table id="temuanTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach( $temuans as $temuan )
                    <tr>
                        <td>{{ $temuan->id }}</td>
                        <td>
                            {{ $temuan->location->name }}<br/>
                            <i class="small">{{ $temuan->location_detail }}</i>
                        </td>
                        <td>{{ $temuan->inspection_date }}</td>
                        <td>
                            <a href="{{ route('temuans.show', ['id'=>$temuan->id]) }}"
                               class="btn btn-sm btn-primary">
                                <i class="fa fa-book"></i>
                            </a>


                                {{--<a href="{{ route('checklists.print', ['id'=>$checklist->id]) }}"--}}
                                   {{--class="btn btn-sm btn-primary">--}}
                                    {{--<i class="fa fa-print"></i>--}}
                                {{--</a>--}}

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#temuanTable').DataTable({
                responsive: true,
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': [ -1 ]
                }]
            });
        });
    </script>
@endsection

resources/views/temuans/print.blade.php
@extends('print_template')

@section('content')
    <div class="row">
        <div class="col-sm-12 invoice-col">
            <b>CETAK TEMUAN</b><br/><br/>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <tr>
            <th width="200">ID Temuan</th>
            <td>{{ $temuan->id }}</td>
        </tr>
        <tr>
            <th>Inspectors</th>
            <td>
                @php($checklist = $temuan->checklist )
                @include( 'walkdowninspectors.inspector_list')
            </td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ $temuan->inspection_date }}</td>
        </tr>
        <tr>
            <th>Location</th>
            <td>{{ $temuan->location->name }}</td>
        </tr>
        <tr>
            <th>Area</th>
            <td>{{ $temuan->location_detail }}</td>
        </tr>
    </table>
    <br/>

    <table id="temuanItemTable" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th width="20">No</th>
            <th>Hazard Class</th>
            <th>Description of Condition</th>
            <th>Corrective Action</th>
            <th>Person/Department Responsible</th>
            <th>Est. Completion Date</th>
            <th>Actual Completion Date</th>
            <th>WO Needed</th>
            <th>Person Completing</th>
            <th>Standard</th>
        </tr>
        </thead>
        <tbody>
        @php ($inc = 1)
        @foreach($temuan->temuanItems as $item)
            <tr>
                <td>{{ $inc }}</td>
                <td>{{ $item->hazardClassString() }}</td>
                <td>
                    {{ $item->description }} <br/>
                    <img style="width: 150px;" src="{{ asset($item->link()) }}" alt="img"/>
                </td>
                <td>
                    {{ $item->corrective_action }} <br/>
                    <img style="width: 150px;" src="{{ asset($item->linkAfter()) }}" alt="img"/>
                </td>
                <td>{{ $item->department_responsible }}</td>
                <td>{{ $item->completion_date_est }}</td>
                <td>{{ $item->completion_date_act }}</td>
                <td>{{ $item->wo_needed }}</td>
                <th>{{ $item->person_completing }}</th>
                <td>{{ $item->standard }}</td>
            </tr>
            @php($inc++)
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/temuans/show.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Detail Temuan
                <a href="{{ route('temuans.print', ['id'=>$temuan->id]) }}" target="_blank"
                   class="btn btn-sm btn-default">
                    <i class="fa fa-print"></i> Cetak
                </a>
            </h3>
        </div>
        <div class="box-body">
            <table id="temuanTable" class="table table-bordered table-striped">
                <tr>
                    <th>ID</th>
                    <td>{{ $temuan->id }}</td>
                </tr>
                <tr>
                    <th>Inspectors</th>
                    <td>
                        @php($checklist = $temuan->checklist )
                        @include( 'walkdowninspectors.inspector_list')
                    </td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ $temuan->inspection_date }}</td>
                </tr>
                <tr>
                    <th>Location</th>
                    <td>{{ $temuan->location->name }}</td>
                </tr>
                <tr>
                    <th>Area</th>
                    <td>{{ $temuan->location_detail }}</td>
                </tr>
            </table>
        </div>
    </div>

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Daftar Item Temuan
                @if( auth()->user()->hasRole('safety') )
                    <a href="{{ route('temuanitems.createbytemuan', ['id'=>$temuan->id]) }}"
                       title="Tambah Baru"
                       class="btn btn-primary btn-sm">
                        <i class="fa fa-plus"></i>
                    </a>
                @endif
            </h3>
        </div>
        <div class="box-body" style="overflow-x: scroll">
            <table id="temuanItemTable" class="table table-bordered table-responsive">
                <thead>
                <tr>
                    <th width="20">No</th>
                    <th width="100">Hazard Class</th>
                    <th>Description of Cond. found</th>
                    <th>Corective Action</th>
                    <th>Detail</th>
                    @if( auth()->user()->hasRole('safety') )
                        <th width="150">Action</th>
                    @endif
                </tr>
                </thead>
                <tbody>
                    @foreach($temuan->temuanItems as $key => $item)
                        <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{ $item->hazardClassString() }}</td>
                            <td>
                                {{ $item->description }} <br/>
                                @if( $item->photo )
                                    <a href="{{ asset($item->link()) }}" data-featherlight="image">
                                        <img class="img-circle" style="width: 50px; height: 50px;" src="{{ asset($item->tumbnail()) }}" alt="img"/>
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $item->corrective_action }} <br/>
                                @if( $item->photo_after )
                                    <a href="{{ asset($item->linkAfter()) }}" data-featherlight="image">
                                        <img class="img-circle" style="width: 50px; height: 50px;" src="{{ asset($item->tumbnailAfter()) }}" alt="img"/>
                                    </a>
                                @endif
                            </td>
                            <td>
                                <dl>
                                    @if($item->department_responsible != null)
                                        <dt>Dept. Responsible</dt><dd>{{ $item->department_responsible }}</dd>
                                    @endif
                                    @if($item->completion_date_est != null)
                                        <dt>Est. Completion Date</dt><dd>{{ $item->completion_date_est }}</dd>
                                    @endif
                                </dl>
                            </td>
                            @if( auth()->user()->hasRole('safety') )
                            <td>
                                <a href="{{ route('temuanitems.edit', ['id'=>$item->id]) }}"
                                   title="Edit Data"
                                   class="btn btn-sm btn-primary">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <form onsubmit="return confirm('Hapus data?');"
                                      id="delete-{{ $item->id }}"
                                      class="hide"
                                      method="POST"
                                      action="{{ route('temuanitems.destroy', ['id'=>$item->id]) }}">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                </form>
                                <a href="javascript:void(0)"
                                   onclick="$('#delete-{{ $item->id }}').submit()"
                                   title="Hapus"
                                   class="btn btn-sm btn-danger">
                                    <i class="fa fa-remove"></i>
                                </a>
                            </td>
                                @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection