routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function () {
    return view('auth_template');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('masterchecklists', 'MasterChecklistController')->except(['show']);
Route::resource('users', 'UserController')->except(['show']);
Route::resource('nearmisses', 'NearmissController');
Route::resource('locations', 'LocationController')->except(['show']);
Route::resource('departments', 'DepartmentController')->except(['show']);

Route::resource('checklists', 'ChecklistController');
Route::resource('checklistitems', 'ChecklistItemController')->only(['edit','update']);
Route::resource('temuans', 'TemuanController');
Route::resource('temuanitems', 'TemuanItemController');

Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin']], function() {

    Route::get('/users/{id}/change-roles', 'UserController@changeRole')->name('change-roles');
    Route::post('/users/{id}/save-roles', 'UserController@saveRole')->name('save-roles');
    Route::get('/users/{id}/loginbyid', 'UserController@loginById')->name('loginbyid');
    Route::get('/users/{id}/reset-password', 'UserController@resetPassword')->name('reset-password');

    Route::get('mastercheklists-by-category/{id}', 'MasterChecklistController@indexByCategory')->name('mastercheklists-by-category');
    Route::get('mastercheklists-create-by-category/{id}', 'MasterChecklistController@createByCategory')->name('mastercheklists-create-by-category');

    Route::put('/departments/{id}/sethead/{user_id}', 'DepartmentController@sethead')->name('sethead');
});

Route::group(['prefix' => '/', 'middleware' => ['auth']], function() {
    Route::get('/change-password/user', 'ChangePasswordController@create')->name('change-password.create');
    Route::post('/change-password/user', 'ChangePasswordController@store')->name('change-password.store');

    Route::get('/checklists/{id}/print', 'ChecklistController@print')->name('checklists.print');
    Route::get('/temuans/{id}/print', 'TemuanController@print')->name('temuans.print');
    Route::get('/nearmisses/{id}/print', 'NearmissController@print')->name('nearmisses.print');
    Route::get('/temuans/{id}/create-by-checklist', 'TemuanController@createByChecklist')->name('temuans.createbychecklist');
    Route::get('/temuanitems/{id}/create-by-temuan', 'TemuanItemController@createByTemuan')->name('temuanitems.createbytemuan');
});

Route::group(['prefix' => '/', 'middleware' => ['role:safety']], function (){
    Route::post('checklistitems/skip-action/{id}/{action}', 'ChecklistItemController@skip')->name('checklistitems.skip');
});
Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin|safety']], function() {
    Route::get('walkdowninspectors/walkdown/{id}/list', 'WalkdownInspectorController@list')->name('walkdowninspectors.list');
    Route::post('walkdowninspectors/walkdown/{id}/add', 'WalkdownInspectorController@add')->name('walkdowninspectors.add');
    Route::delete('walkdowninspectors/{id}/delete', 'WalkdownInspectorController@destroy')->name('walkdowninspectors.destroy');
});

app/Models/MasterChecklist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MasterChecklist extends Model
{
    
    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }
}

app/Http/Controllers/MasterChecklistController.php
<?php

namespace App\Http\Controllers;

use App\Forms\MasterChecklistForm;
use App\Models\MasterChecklist;
use App\Models\Category;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class MasterChecklistController extends Controller
{
    use FormBuilderTrait;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin|superadmin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexByCategory($id)
    {
        $category = Category::find($id);
        
        $page_title = 'Daftar Master Ceklist';
        $masterchecklists = $category->mastercheklists;
        
        return view('masterchecklists.index', compact('masterchecklists', 'category', 'page_title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createByCategory($id)
    {
        $category = Category::where('id', $id)->first();
        $page_title = 'Buat Master Checklist';
        $page_description = 'Untuk kategori '.$category->name;
        $masterchecklist = new MasterChecklist();
        $masterchecklist->category_id = $category->id;
        
        $form = $this->form(MasterChecklistForm::class, [
            'method' => 'POST',
            'model' => $masterchecklist,
            'url' => route('masterchecklists.store')
        ]);
        
        return view('masterchecklists.create', compact('form', 'page_title', 'page_description'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(MasterChecklistForm::class);
        
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }
        
        $data = $form->getFieldValues();
        
        $masterchecklist = new MasterChecklist();
        $masterchecklist->question = $data['question'];
        $masterchecklist->category_id = $data['category_id'];
        $masterchecklist->save();

        flash('Data berhasil disimpan.')->success();
        return redirect('/mastercheklists-by-category/'.$data['category_id']);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $masterchecklist = MasterChecklist::find($id);
        $page_title = 'Edit Ceklist #'.$masterchecklist->id;
        
        $form = $this->form(MasterChecklistForm::class, [
            'method'    => 'PUT',
            'url' => route('masterchecklists.update', ['id' => $masterchecklist->id]),
            'model' => $masterchecklist
        ]);
        
        return view('masterchecklists.edit', compact('form', 'page_title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(MasterChecklistForm::class);
        
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }
        
        $data = $form->getFieldValues();
        $masterchecklist = MasterChecklist::find($id);
        $masterchecklist->question = $data['question'];
        $masterchecklist->save();

        flash('Data berhasil diubah.')->success();
        return redirect('/mastercheklists-by-category/'.$data['category_id']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $masterchecklist = MasterChecklist::find($id);
        $category_id = $masterchecklist->category_id;
        $masterchecklist->delete();

        flash('Data berhasil dihapus.')->success();
        return redirect('/mastercheklists-by-category/'.$category_id);
    }
}

resources/views/masterchecklists/create.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
          <h3 class="box-title">
              Form Master Ceklist Baru
          </h3>
        </div>
        <!-- /.box-header -->
            
        <div class="box-body">
            {!! form($form) !!}
        </div>
    </div>

@endsection

resources/views/masterchecklists/edit.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
          <h3 class="box-title">
              Form Master Ceklist
          </h3>
        </div>
        <!-- /.box-header -->
            
        <div class="box-body">
            {!! form($form) !!}
        </div>
    </div>

@endsection

resources/views/masterchecklists/index.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Detail Kategori
            </h3>
        </div>
        <div class="box-body">
            <table id="categoryTable" class="table table-bordered table-striped">
                <tr>
                    <th>Nama</th>
                    <td>{{ $category->name }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Tabel Master Ceklist
                <a href="{{ route('mastercheklists-create-by-category', ['id'=>$category->id]) }}"
                   title="Tambah Baru"
                   class="btn btn-primary btn-sm">
                    <i class="fa fa-plus"></i>
                </a>
            </h3>
        </div>
        <div class="box-body" style="overflow-x: scroll">
            <table id="checklistTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Pertanyaan</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $masterchecklists as $masterchecklist )
                        <tr>
                            <td>{{ $masterchecklist->id }}</td>
                            <td>{{ $masterchecklist->question }}</td>
                            <td>
                                <a href="{{ route('masterchecklists.edit', ['id'=>$masterchecklist->id]) }}" title="Edit"
                                    class="btn btn-sm btn-primary">
                                     <i class="fa fa-edit"></i>
                                 </a>
                                 <form onsubmit="return confirm('Hapus data?');" 
                                       id="delete-{{ $masterchecklist->id }}"
                                       class="hide"
                                       method="POST" 
                                       action="{{ route('masterchecklists.destroy', ['id'=>$masterchecklist->id]) }}">
                                     {{ method_field('DELETE') }}
                                     {{ csrf_field() }}
                                 </form>
                                 <a href="javascript:void(0)" title="Hapus"
                                    onclick="$('#delete-{{ $masterchecklist->id }}').submit()"
                                    class="btn btn-sm btn-danger">
                                     <i class="fa fa-remove"></i>
                                 </a>
                                
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#checklistTable').DataTable({
                responsive: true,
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': [ -1 ]
                }]
            });
        });
    </script>
@endsection