routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', function () {
    return view('auth_template');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')->except(['show']);
Route::resource('masterchecklists', 'MasterChecklistController')->except(['show']);
Route::resource('users', 'UserController')->except(['show']);
Route::resource('nearmisses', 'NearmissController');
Route::resource('locations', 'LocationController')->except(['show']);
Route::resource('departments', 'DepartmentController')->except(['show']);

Route::resource('checklists', 'ChecklistController');
Route::resource('checklistitems', 'ChecklistItemController')->only(['edit','update']);
Route::resource('temuans', 'TemuanController');
Route::resource('temuanitems', 'TemuanItemController');

Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin']], function() {

    Route::get('/users/{id}/change-roles', 'UserController@changeRole')->name('change-roles');
    Route::post('/users/{id}/save-roles', 'UserController@saveRole')->name('save-roles');
    Route::get('/users/{id}/loginbyid', 'UserController@loginById')->name('loginbyid');
    Route::get('/users/{id}/reset-password', 'UserController@resetPassword')->name('reset-password');

    Route::get('mastercheklists-by-category/{id}', 'MasterChecklistController@indexByCategory')->name('mastercheklists-by-category');
    Route::get('mastercheklists-create-by-category/{id}', 'MasterChecklistController@createByCategory')->name('mastercheklists-create-by-category');

    Route::put('/departments/{id}/sethead/{user_id}', 'DepartmentController@sethead')->name('sethead');
});

Route::group(['prefix' => '/', 'middleware' => ['auth']], function() {
    Route::get('/change-password/user', 'ChangePasswordController@create')->name('change-password.create');
    Route::post('/change-password/user', 'ChangePasswordController@store')->name('change-password.store');

    Route::get('/checklists/{id}/print', 'ChecklistController@print')->name('checklists.print');
    Route::get('/temuans/{id}/print', 'TemuanController@print')->name('temuans.print');
    Route::get('/nearmisses/{id}/print', 'NearmissController@print')->name('nearmisses.print');
    Route::get('/temuans/{id}/create-by-checklist', 'TemuanController@createByChecklist')->name('temuans.createbychecklist');
    Route::get('/temuanitems/{id}/create-by-temuan', 'TemuanItemController@createByTemuan')->name('temuanitems.createbytemuan');
});

Route::group(['prefix' => '/', 'middleware' => ['role:safety']], function (){
    Route::post('checklistitems/skip-action/{id}/{action}', 'ChecklistItemController@skip')->name('checklistitems.skip');
});
Route::group(['prefix' => '/', 'middleware' => ['role:admin|superadmin|safety']], function() {
    Route::get('walkdowninspectors/walkdown/{id}/list', 'WalkdownInspectorController@list')->name('walkdowninspectors.list');
    Route::post('walkdowninspectors/walkdown/{id}/add', 'WalkdownInspectorController@add')->name('walkdowninspectors.add');
    Route::delete('walkdowninspectors/{id}/delete', 'WalkdownInspectorController@destroy')->name('walkdowninspectors.destroy');
});

app/Models/Checklist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Checklist extends Model
{


    public function creator()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function checklistItems()
    {
        return $this->hasMany('App\Models\ChecklistItem', 'checklist_id', 'id');
    }

    public function inspectors()
    {
        return $this->hasMany('App\Models\WalkdownInspector', 'checklist_id', 'id');
    }

    public function indexedInspector()
    {
        $data = array();
        foreach ($this->inspectors as $inspector) {
            $user = $inspector->inspector;
            $data[$user->department->name][$user->id] = $user->name;
        }
        return $data;
    }

    public function getItemsIndexByCategory(){

        $arr = array();
        foreach ($this->checklistItems as $checklistItem) {
            $arr[$checklistItem->category][] = $checklistItem;
        }

        return $arr;
    }

    public function getChecklistItemCategory(){

        $arr = array();
        foreach ($this->checklistItems as $checklistItem)
        {
            if(!$checklistItem->skip)
            {
                $arr[$checklistItem->category_id] = $checklistItem->category;
            }
        }

        return $arr;
    }

    public function getSkipedCategories(){

        $arr = array();
        foreach ($this->checklistItems as $checklistItem)
        {
            if($checklistItem->skip)
            {
                $arr[$checklistItem->category_id] = $checklistItem->category;
            }
        }

        return $arr;
    }

    public function getChecklistItemsByCategoryId($id){

        $arr = array();
        foreach ($this->checklistItems as $checklistItem)
        {
            if($checklistItem->category_id == $id)
            {
                $arr[$checklistItem->id] = $checklistItem;
            }
        }

        return $arr;
    }

    public function getItemsIndexByCategoryForPrint(){

        $arr = array();
        foreach ($this->checklistItems as $checklistItem)
        {
            if(!$checklistItem->skip) {
                $arr[$checklistItem->category][] = $checklistItem;
            }
        }

        return $arr;
    }

    public function getItemUnanswered(){

        $item = ChecklistItem::where(['checklist_id' => $this->id, 'answered' => false, 'skip' => false])
            ->orderBy('order', 'asc')
            ->first();
        return $item;

    }

    public function location()
    {
        return $this->belongsTo('App\Models\Location');
    }

    public function temuan()
    {
        return $this->hasOne('App\Models\Temuan');
    }
}

app/Http/Controllers/ChecklistController.php
<?php

namespace App\Http\Controllers;

use App\Forms\ChecklistForm;
use App\Models\Category;
use App\Models\Checklist;
use App\Models\ChecklistItem;
use App\Models\Temuan;
use App\Models\WalkdownInspector;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class ChecklistController extends Controller
{
    use FormBuilderTrait;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin|superadmin|safety');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'Daftar Walkdown';
        $page_description = 'Walkdown';

        if(Auth::user()->hasRole('admin')){
            $checklists = Checklist::all();
        }else{
            $checklists = Auth::user()->checklistCreated;
        }

        return view('checklists.index', compact('checklists', 'page_title', 'page_description'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Buat Walkdown';

        $form = $this->form(ChecklistForm::class, [
            'method' => 'POST',
            'url' => route('checklists.store')
        ]);

        return view('checklists.create', compact('form', 'page_title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(ChecklistForm::class);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->getFieldValues();

        // create checklist
        $checklist = new Checklist;
        $checklist->user_id = Auth::user()->id;
        $checklist->location_id = $data['location_id'];
        $checklist->location_detail = $data['location_detail'];
        $checklist->inspection_date = $data['inspection_date'];
        $checklist->save();

        $wi = new WalkdownInspector();
        $wi->checklist_id = $checklist->id;
        $wi->user_id = Auth::user()->id;
        $wi->save();

        // create temuan
        $temuan = new Temuan;
        $temuan->user_id = Auth::user()->id;
        $temuan->checklist_id = $checklist->id;
        $temuan->location_id = $data['location_id'];
        $temuan->location_detail = $data['location_detail'];
        $temuan->inspection_date = $data['inspection_date'];
        $temuan->save();

        //get category
        $checklist_categories = Category::all();
        $order = 1;
        //save checklist item
        foreach ($checklist_categories as $category) {

            // get master checklist
            $mcs = $category->mastercheklists;
            foreach ($mcs as $mc) {
                $item = new ChecklistItem;
                $item->checklist_id = $checklist->id;
                $item->category_id = $category->id;
                $item->master_checklist_id = $mc->id;
                $item->category = $category->name;
                $item->question = $mc->question;
                $item->order = $order;
                $item->save();

                $order++;
            }
        }

        flash('Data berhasil disimpan.')->success();
        return redirect('/checklists');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $checklist = Checklist::find($id);
        $page_title = 'Daftar Item Cheklist';

        return view('checklists.show', compact('checklist', 'page_title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $checklist = Checklist::find($id);
        $page_title = 'Edit Walkdown #'.$checklist->id;

        $form = $this->form(ChecklistForm::class, [
            'method'    => 'PUT',
            'url' => route('checklists.update', ['id' => $checklist->id]),
            'model' => $checklist
        ]);

        return view('checklists.edit', compact('form', 'page_title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(ChecklistForm::class);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->getFieldValues();
        $checklist = Checklist::find($id);
        $checklist->location_id = $data['location_id'];
        $checklist->location_detail = $data['location_detail'];
        $checklist->inspection_date = $data['inspection_date'];
        $checklist->save();


        // update temuan
        $temuan = Temuan::where('checklist_id', $checklist->id)->first();
        $temuan->location_id = $data['location_id'];
        $temuan->location_detail = $data['location_detail'];
        $temuan->inspection_date = $data['inspection_date'];
        $temuan->save();

        flash('Data berhasil diubah.')->success();
        return redirect('/checklists');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $checklist = Checklist::find($id);
        $checklist->delete();

        flash('Data berhasil dihapus.')->success();
        return redirect('/checklists');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function print($id)
    {
        $checklist = Checklist::find($id);
        $unanswered = $checklist->getItemUnanswered();
        if ($unanswered)
        {
            flash('Terdapat item checklist yang belum diisi, lengkapi pengisian checklist sebelum mencetak.')->error();
            return redirect()->back();
        }

        return view('checklists.print', compact('checklist'));
    }
}

resources/views/checklists/create.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
          <h3 class="box-title">
              Form Checklist
          </h3>
        </div>
        <!-- /.box-header -->
            
        <div class="box-body">
            {!! form($form) !!}
        </div>
    </div>

@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            //Date picker
            $('.datepicker').datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
@endsection

resources/views/checklists/edit.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
          <h3 class="box-title">
              Form Checklist
          </h3>
        </div>
        <!-- /.box-header -->
            
        <div class="box-body">
            {!! form($form) !!}
        </div>
    </div>

@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            //Date picker
            $('.datepicker').datepicker({
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
@endsection

resources/views/checklists/index.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Tabel Checklist
                @if( auth()->user()->hasRole('safety') )
                    <a href="{{ route('checklists.create') }}"
                       class="btn btn-primary btn-sm">
                        <i class="fa fa-plus"></i>
                    </a>
                @endif
            </h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body" style="overflow-x: scroll">
            <table id="checklistTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Inspector</th>
                    <th>Lokasi</th>
                    <th>Tanggal</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach( $checklists as $checklist )
                    <tr>
                        <td>{{ $checklist->id }}</td>
                        <td>{{ $checklist->creator->name }}</td>
                        <td>
                            {{ $checklist->location->name }}<br/>
                            <i class="small">{{ $checklist->location_detail }}</i>
                        </td>
                        <td>
                            {{ $checklist->inspection_date }}
                        </td>
                        <td>
                            <a href="{{ route('checklists.show', ['id'=>$checklist->id]) }}" title="Tampilkan Checklist"
                               class="btn btn-sm btn-primary">
                                <i class="fa fa-check"></i> Checklist
                            </a>
                            <a href="{{ route('temuans.show', ['id'=>$checklist->temuan->id]) }}" title="Tampilkan Temuan"
                               class="btn btn-sm btn-primary">
                                <i class="fa fa-search"></i> Temuan
                            </a>
                            <a href="{{ route('checklists.edit', ['id'=>$checklist->id]) }}" title="Edit Data Walkdown"
                               class="btn btn-sm btn-primary">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="{{ route('walkdowninspectors.list', ['id'=>$checklist->id]) }}" title="Tambah data Inspector"
                               title="Daftar Inspector"
                               class="btn btn-sm btn-default">
                                <i class="fa fa-users"></i>
                            </a>
                            <span class="dropdown">
                                <button id="dropdownPrint" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-default dropdown-toggle" type="button">
                                    <i class="fa fa-print"></i>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('checklists.print', ['id'=>$checklist->id]) }}" target="_blank">Checklist</a></li>
                                    <li><a href="{{ route('temuans.print', ['id'=>$checklist->temuan->id]) }}" target="_blank">Temuan</a></li>
                                </ul>
                            </span>
                            <form onsubmit="return confirm('Hapus Checklist?');"
                                  id="delete-{{ $checklist->id }}"
                                  class="hide"
                                  method="POST"
                                  action="{{ route('checklists.destroy', ['id'=>$checklist->id]) }}">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                            </form>
                            <a href="javascript:void(0)" title="Hapus"
                               onclick="$('#delete-{{ $checklist->id }}').submit()"
                               class="btn btn-sm btn-danger">
                                <i class="fa fa-remove"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@section('inline-script')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#checklistTable').DataTable({
                responsive: true,
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': [ -1 ]
                }]
            });
        });
    </script>
@endsection

resources/views/checklists/print.blade.php
@extends('print_template')

@section('content')
    <div class="row">
        <div class="col-sm-12 invoice-col">
            <b>CETAK CHECKLIST</b><br/><br/>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <tr>
            <th>ID Checklist</th>
            <td>{{ $checklist->id }}</td>
        </tr>
        <tr>
            <th>Inspector</th>
            <td>
                @include( 'walkdowninspectors.inspector_list')
            </td>
        </tr>
        <tr>
            <th>Lokasi</th>
            <td>{{ $checklist->location->name }}</td>
        </tr>
        <tr>
            <th>Tanggal</th>
            <td>{{ $checklist->inspection_date }}</td>
        </tr>
    </table>
    <table id="checklistTable" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>No</th>
            <th>Pertanyaan</th>
            <th>Jawaban</th>
            <th>Detail</th>
            <th>Photo</th>
        </tr>
        </thead>
        <tbody>
        @php( $inc1 = 1 )
        @foreach( $checklist->getItemsIndexByCategoryForPrint() as $key => $items )
            <tr>
                <td><strong>{{ $inc1 }}</strong></td>
                <td colspan="3"><strong>{{ $key }}</strong></td>
            </tr>
            @php( $inc2 = 1 )
            @foreach($items as $item)
                <tr>
                    <td>{{ $inc1 }}.{{ $inc2 }}</td>
                    <td>{{ $item->question }}</td>
                    <td>
                        {{ $item->answerString() }}<br/>
                    </td>
                    <td>{{ $item->detail }}</td>
                    <td>
                        @if( $item->photo )
                            <img style="width: 200px;" src="{{ asset($item->tumbnail()) }}" alt="img"/>
                        @endif
                    </td>
                </tr>
                @php( $inc2++ )
            @endforeach
            @php( $inc1++ )
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/checklists/show.blade.php
@extends('admin_template')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Detail Checklist
                <a href="{{ route('checklists.print', ['id'=>$checklist->id]) }}" target="_blank"
                   class="btn btn-sm btn-default">
                    <i class="fa fa-print"></i> Cetak
                </a>
            </h3>
        </div>
        <div class="box-body">
            <table id="checklistTable" class="table table-bordered table-primary">
                <tr>
                    <th>ID</th>
                    <td>{{ $checklist->id }}</td>
                </tr>
                <tr>
                    <th>Inspector</th>
                    <td>
                        @include( 'walkdowninspectors.inspector_list')
                    </td>
                </tr>
                <tr>
                    <th>Tanggal</th>
                    <td>{{ $checklist->inspection_date }}</td>
                </tr>
                <tr>
                    <th>Lokasi</th>
                    <td>{{ $checklist->location->name }}</td>
                </tr>
                <tr>
                    <th>Area</th>
                    <td>{{ $checklist->location_detail }}</td>
                </tr>
            </table>
        </div>
    </div>

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Daftar Item Cheklist
                @php( $itemUnanswered = $checklist->getItemUnanswered())
                @role('safety')
                    @if( $itemUnanswered != null )
                        <a href="{{ route('checklistitems.edit', ['id'=>$itemUnanswered->id]) }}" title="Mulai Isi Checklist"
                           class="btn btn-primary btn-sm">
                            <i class="fa fa-play"></i>
                        </a>
                    @endif
                @endrole
            </h3>
        </div>
        <div class="box-body" style="overflow-x: scroll">
            <table id="checklistTable" class="table table-bordered table-responsive">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Pertanyaan</th>
                    <th>Jawaban (Ya/Tidak)</th>
                    <th>Photo</th>
                    @role('safety')
                        <th>Action</th>
                    @endrole
                </tr>
                </thead>
                <tbody>
                @php( $inc1 = 1 )
                @foreach( $checklist->getChecklistItemCategory() as $key => $category )
                    <tr>
                        <td><strong>{{ $inc1 }}</strong></td>
                        <td colspan="4">
                            <strong>{{ $category }}</strong>
                            <form onsubmit="return confirm('Semua data yg telah diisi pada kategori ini akan terhapus, tandai tidak diisi?');"
                                  id="skip-{{ $key }}"
                                  class="hide"
                                  method="POST"
                                  action="{{ route('checklistitems.skip', ['id'=>$key, 'action'=>'skip']) }}">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}
                            </form>
                            <a href="javascript:void(0)"
                               onclick="$('#skip-{{ $key }}').submit()"
                               class="btn btn-xs btn-warning">
                                <i class="fa fa-check-circle-o"></i> tandai tidak diisi
                            </a>
                        </td>
                    </tr>
                    @php( $inc2 = 1 )

                    @foreach($checklist->getChecklistItemsByCategoryId($key) as $item)
                        <tr>
                            <td>{{ $inc1 }}.{{ $inc2 }}</td>
                            <td>
                                {{ $item->question }}<br/>
                            </td>
                            <td>
                                {{ $item->answerString() }}<br/>
                                <i style="color: dodgerblue" class="small">{{ $item->detail }}</i>
                            </td>
                            <td>
                                @if( $item->photo )
                                    <a href="{{ asset($item->link()) }}" data-featherlight="image">
                                        <img class="img-circle" style="width: 50px; height: 50px;" src="{{ asset($item->tumbnail()) }}" alt="img"/>
                                    </a>
                                @endif
                            </td>
                            @role('safety')
                            <td>
                                <a href="{{ route('checklistitems.edit', ['id'=>$item->id]) }}"
                                   class="btn btn-sm btn-primary">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            @endrole
                        </tr>
                        @php( $inc2++ )
                    @endforeach
                    @php( $inc1++ )
                @endforeach
                </tbody>
            </table>
            <br/>
        </div>
    </div>

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Kategori Ditandai tidak diisi</h3>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Nama Kategori</th>
                </tr>
                </thead>
                <tbody>
                @foreach($checklist->getSkipedCategories() as $key => $category)
                    <tr>
                        <td>
                            {{ $category }}
                            <form onsubmit="return confirm('Tandai harus diisi?');"
                                  id="unskip-{{ $key }}"
                                  class="hide"
                                  method="POST"
                                  action="{{ route('checklistitems.skip', ['id'=>$key, 'action'=>'unskip']) }}">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}
                            </form>
                            <a href="javascript:void(0)"
                               onclick="$('#unskip-{{ $key }}').submit()"
                               class="btn btn-xs btn-success">
                                <i class="fa fa-check-circle-o"></i> tandai harus diisi
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection